CC=gcc
CFLAGS=-g -O2 -Wall -I.
OBJS=\
	cbtcommon/debug.o\
	cbtcommon/hash.o\
	cbtcommon/text_util.o\
	cvsps.o

cvsps: $(OBJS)
	gcc -o cvsps $(OBJS)

install:
	install cvsps /usr/local/bin

.PHONY: install
